---
- name: "[APACHE] -  Required and recommended packages are installed."
  package: "name={{ item }} state=present"
  with_items:
    - apache2
    - smbclient
    - "libapache2-mod-php{{ php_ver }}"
    - "php{{ php_ver }}-ldap"
    - "php{{ php_ver }}-imap"
    - "php{{ php_ver }}-gd"
    - "php{{ php_ver }}-json"
    - "php{{ php_ver }}-curl"
    - "php{{ php_ver }}-intl"
    - "php{{ php_ver }}-mcrypt"
  notify: start apache

- name: "[APACHE] -  Some other packages are installed."
  package: "name={{ item }} state=present"
  with_items: "{{ php_pkg_spe }}"

- name: "[APACHE] -  APCu is installed."
  package: "name={{ php_pkg_apcu }} state=present"
  when : ansible_distribution_release not in [ "trusty" ]

- block:
  # load APCu from backports as the default version for trusty is obsolete.
  - name: "[APACHE] -  Configure trusty backports."
    apt_repository:
      repo: "deb http://fr.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse"
      state: present
      update_cache: yes
    ignore_errors: yes # fix for travis ci
  - name: "[APACHE] -  Install APCu from backports."
    apt: "name={{ php_pkg_apcu }} state=latest default_release=trusty-backports"
  when: ansible_distribution_release == "trusty"

- name: "[APACHE] -  enable APC for php CLI"
  lineinfile:
    dest: "{{ php_dir }}/cli/php.ini"
    line: "apc.enable_cli = 1"
    insertbefore: "^; End:$"
    state: present
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"

- name: "[APACHE] -  Required Apache2 modules are enabled"
  apache2_module: state=present name={{ item }}
  with_items:
    - ssl
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify: restart apache

- name: "[APACHE] -  generate Nextcloud configuration for apache"
  template:
    dest: /etc/apache2/sites-available/nc_{{ nextcloud_instance_name }}.conf
    src: "{{nextcloud_websrv_template}}"
  notify: reload apache

- name: "[APACHE] -  Enable Nextcloud site in apache conf"
  file:
    path: /etc/apache2/sites-enabled/nc_{{ nextcloud_instance_name }}.conf
    src: /etc/apache2/sites-available/nc_{{ nextcloud_instance_name }}.conf
    state: link
  notify: reload apache
