---
- name: "[NC-DL] - Unzip is installed"
  package: name=unzip state=installed
  when: nextcloud_archive_format == "zip"

- name: "[NC-DL] - bunzip2 is installed"
  package: name=bzip2 state=installed
  when: nextcloud_archive_format == "tar.bz2"

- block:
  - name: "[NC-DL] - Create the download link for *latest*."
    set_fact:
      nextcloud_full_url: "{{nextcloud_repository}}/{{nextcloud_version_channel}}/{{[nextcloud_dl_file_name.latest, nextcloud_archive_format]|join('.')}}"
    when: nextcloud_get_latest and (nextcloud_version_channel != 'prereleases')

  - name: "[NC-DL] - Create the download link."
    set_fact:
      nextcloud_full_url: "{{nextcloud_repository}}/{{nextcloud_version_channel}}/{{[nextcloud_dl_file_name[nextcloud_version_channel], nextcloud_archive_format]|join('.')}}"
    when: (not nextcloud_get_latest) or (nextcloud_version_channel == 'prereleases')
  when: nextcloud_full_url is not defined

- block:
  - name: "Download & extract Nextcloud to /tmp."
    unarchive:
      copy: no
      src: "{{ nextcloud_full_url }}"
      dest: "/tmp/"

  - name: "[NC-DL] - Move extracted files to {{ nextcloud_webroot }}."
    command: "cp -r /tmp/nextcloud/. {{ nextcloud_webroot }}/"

  - name: "[NC-DL] - Remove nextcloud archive files"
    file: path=/tmp/nextcloud state=absent
